# C-Cleanup-And-Exception-Unwinding
These 2 C++ programs demonstrate some behind the scenes operations of C++ that occur if an exception is thrown. The first program demonstrates that objects created in a try block are automatically destroyed if an exception is thrown. The second program demonstrates that unwinding of the stack occurs if an exception is thrown.
